server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

# security
jwt:
  access-token:
    secret: ${ACCESS_SECRET}
    expiration: ${ACCESS_EXPIRATION}
  confirm-token:
    secret: ${CONFIRM_SECRET}
    expiration: ${CONFIRM_EXPIRATION}

# email
email:
  username: ${EMAIL_USERNAME}
  password: ${EMAIL_PASSWORD}
  host: ${EMAIL_HOST}